### PR TITLE
Here is the fancy .... the really fancy

### PR DESCRIPTION
**Pull request by aodzip**

### CODE REVIEW

**Comment by kdani1** [comment]
Hello I found a Bug, a Big Bug :D 
When a player get more damage than players health, the player cannot respawn and have to click to main menu and join again sorry for my bad english i hope somebody can help me!

**Comment by thebigsmileXD** [comment]
The first I should be capital.

**Comment by keithkfng** [comment]
No. Look at the logo.

**Comment by thebigsmileXD** [comment]
Oh.. but why is the Repo name/pocketmine group name ImagicalMine then?

**Comment by keithkfng** [comment]
More punctuated...

**Pull request merged**
