### PR TITLE
Fix Window's 10 3X3 and 2x2 Crafting

### PR DESCRIPTION
**Pull request by yungtechboy1**
This fixes the crafting for Windows 10 2x2 and 3x3

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Cant be automatically merged.

**Comment by keithkfng** [comment]
Someone made a conflict -_-

**Comment by matcracker** [comment]
@PeratX :P

**Comment by thebigsmileXD** [comment]
Still need to join this? @keithkfng

**Comment by matcracker** [comment]
No, It have a conflict...

**Comment by thebigsmileXD** [comment]
@matcracker The question was: "Still NEED to merge this?", if so, i'll check why theres a conflict

**Comment by BlackShadow1** [comment]
beacause my pull request is merged first of this with same file modified..

**Comment by thebigsmileXD** [comment]
@BlackShadow1 so close this?

**Comment by matcracker** [comment]
Yep

**Comment by BlackShadow1** [comment]
sorry for my english, with same NAME file modified, lol

**Pull request closed without merging**
