### PR TITLE
Added sticks crafting

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by BlackShadow1** [comment]
Damn desktop version..

**Comment by BlackShadow1** [comment]
Thanks, i had forgot the amount XD

**Comment by SalmonGER** [comment]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/inventory/CraftingManager.php#L95

Uhm, it's already there.

**Comment by BlackShadow1** [comment]
Anyone says this isn't in the crafting racipe... Sorry.

**Comment by zzm317** [comment]
Fixed

**Comment by BlackShadow1** [comment]
Well

**Pull request closed without merging**
