### PR TITLE
BIG IMAGICALMINE RENAME

### PR DESCRIPTION
**Pull request by keithkfng**
This means that you will need to delete some of your files, here is a list -
- PocketMine-MP.phar(changes to ImagicalMine.phar)<br>
And you won't see a trace of PocketMine really. Got any comments before I merge this?

Jenkins project: http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine-Update/

UPDATE GUIDE:
1. Delete the files above.
2. Get the latest phar from Jenkins.
3. Rename it to ImagicalMine.phar(DO NOT RENAME IT TO "PocketMine-MP.phar"!)
4. You're done! Simply start the server again to complete the update!

### CODE REVIEW

**Comment by keithkfng** [comment]
Jenkins test passed XD

**Comment by thebigsmileXD** [comment]
Yes, i have a comment. Some plugins access the pocketmine.yml with that name.

**Comment by keithkfng** [comment]
-_-

**Comment by keithkfng** [comment]
@thebigsmileXD reverted back. D:

**Comment by keithkfng** [comment]
Going to merge this...

**Comment by aodzip** [comment]
change the pocketmine.yml is not a good idea.
But you can create a new config imagicalmine.yml and load it at startup

**Comment by lolcraftboy14** [comment]
It dont work on android ):

**Comment by keithkfng** [comment]
Yes, sorry. It's because the app looks for PocketMine-MP.phar. Rename to it PocketMine-MP.phar if you're on Android then.

**Comment by lolcraftboy14** [comment]
Oke

**Comment by lolcraftboy14** [comment]
It dont work

**Comment by lolcraftboy14** [comment]
Never mint

**Comment by robske110** [comment]
Has Pocketmine.yml been reverted yet?

**Comment by thebigsmileXD** [comment]
WEll, again. We should not rename it.

**Comment by remotevase** [comment]
link is not working for me...

**Comment by ZhenMC** [comment]
Link is Working?

**Comment by remotevase** [comment]
No

**Pull request merged**
