### PR TITLE
Food rewrite.

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Want to see the issues

### CODE REVIEW

**Comment by PocketKiller** [comment]
conflicts..

**Comment by thebigsmileXD** [comment]
I know, i wrote: "Want to see the conflicts"!!!!!!!!!!!!!!

**Comment by BlackShadow1** [comment]
Because some files are already rewrited before this and generate the conflicts..

**Comment by thebigsmileXD** [comment]
@BlackShadow1 i know that.

**Comment by matcracker** [comment]
Conflicts!! 1! 1!! 1 

-__-

**Comment by BlackShadow1** [comment]
@matcracker xD

**Comment by BlackShadow1** [comment]
@thebigsmileXD try to resolve the conflict, i need this branch for fix brewing stand D:

**Comment by thebigsmileXD** [comment]
fugithub

**Comment by thebigsmileXD** [comment]
Sorry, image bug, BUT FUCK YOU GITHUB.
NOW THE ONLY THING I GET IS "error"

**Comment by BlackShadow1** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/f091eb2bba5615fb02c77fbb3391b0a994a6c0cf
https://github.com/ImagicalCorp/ImagicalMine/commit/4cd6acf4e166bf2ddce3867cca7096a261fc025b

**Comment by matcracker** [comment]
Follow this steps:
1) Save a copy of your branch
2) Merge the master branch into food branch
3) Commit your change and check ;)

**Comment by thebigsmileXD** [comment]
@matcracker i am just TRYING to do this for 5 minutes..

**Comment by matcracker** [comment]
D:

**Comment by thebigsmileXD** [comment]
GITHUMB IS TOO DUMB TO SHIT

**Comment by BlackShadow1** [comment]
I think this too @thebigsmileXD

**Comment by thebigsmileXD** [comment]
Thats it, fuck you GitHub. I am out.

**Comment by thebigsmileXD** [comment]
I can't even fork this branch to my local machine anymore.

**Comment by BlackShadow1** [comment]
Noooooooo... FUCK GITHUB FUCK FUCK

**Pull request closed without merging**
