### PR TITLE
Added block and ingot recipe and cleaned unused code

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by aodzip** [comment]
Travis CI failed check the code plz

**Comment by BlackShadow1** [comment]
Spacing problem I think

**Comment by aodzip** [comment]
No . Check again
And why you remove these line?

**Comment by BlackShadow1** [comment]
Because the foreach is unused to the code, i've test it, foreach is for $ingot to $block, but it's buggy. I've deleted it and replaced with the recipe.

**Pull request merged**
