### PR TITLE
Fix one bug of #427

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by matcracker** [comment]
No wait... Don't delete, replace 12 with 11

**Comment by BlackShadow1** [comment]
Sorry..

**Comment by thebigsmileXD** [comment]
Did

**Comment by BlackShadow1** [comment]
Well, but can anyone fix the uncraftable stick, stairs etc.? Is the https://github.com/ImagicalCorp/ImagicalMine/commit/0af7911c6ed68db7f4883ed0f1c81918f0441d66 that cause this bug, can anyone revert or fix this?

**Pull request merged**
