### PR TITLE
Fixed weird display style on ban

### PR DESCRIPTION
**Pull request by robske110**
I need help with editing the kick function, that it accepts completly override of the sended message (You have been banned! Reason: "...")
At the moment it is: (You have been kicked! Reason: "...")

TODO:
Edit the kick function to accept the attribute overrideMsg

### CODE REVIEW

**Comment by matcracker** [comment]
You can't... It's default on client. (I'm seems)

**Comment by thebigsmileXD** [comment]
Its caused by close()

**Comment by robske110** [comment]
Ok, so we can't fix this :(

**Comment by robske110** [comment]
Please reopen this!
/**
* Note for plugin developers: use kick() with the isAdmin
* flag set to kick without the "Kicked by admin" part instead of this method.
*
* @param string $message Message to be broadcasted
* @param string $reason Reason showed in console
* @param bool $notify
*/
Found that!

**Comment by PocketKiller** [comment]
Now what? add a commit on this.

**Comment by robske110** [comment]
Ok, at least i got that one working again...
Here is my try to add isAdmin:
```php
		if(($player = $sender->getServer()->getPlayerExact($name)) instanceof Player){
			if($reason == ""){
				$player->kick("Banned by admin");
			}
			else
			{
				$player->kick("$reason");
			}
		}
```

**Comment by robske110** [comment]
So the pull request is stable now, but we still want to remove that You have been kicked: Reason

**Comment by kam187** [comment]
Erm both bits of code do the same thing before and after?

**Comment by kam187** [comment]
$player->kick($reason !== "" ? "Banned by admin. Reason: " . $reason : "Banned by admin.");
mean:

if ($reason !== "") $player->kick("Banned by admin. Reason: " . $reason)
else
$player->kick("Banned by admin.");

**Comment by robske110** [comment]
No, on ban with specified reason this only puts out that: Kicked by admin! Reason: Bla...
Before it putted out: Kicked by admin! Banned by admin! Reason: Bla
image
image
image

**Comment by kam187** [comment]
oh i see. 

$player->kick($reason !== "" ? $reason : "Banned by admin.");

is more concise then.

**Comment by Naniiii** [comment]
Shouldn't join/leave/kick/ban messages be configurable by owners? Just asking.

**Comment by keithkfng** [comment]
A plugin should have the functionality.

**Comment by robske110** [comment]
We could also implement that here, but we first must manage to give the kick function the isAdmin attribute

**Comment by keithkfng** [comment]
@robske110 you could try make a config in pocketmine.yml for it

**Comment by thebigsmileXD** [comment]
We shouldn't mess this up, and also if we wouldn't mess it up.. I thinks this currently is irrelevant, there are much more important things.

**Comment by robske110** [comment]
Understand that, btw this pull request is already mergeable..
But still want to say Ban instead of kick

**Comment by PocketKiller** [comment]
Thanks @robske110, i found the way.

**Pull request closed without merging**
