### PR TITLE
Fix #390

### LINKED ISSUE #390: SERVER CRASH BREWING STAND
Server crash!
Please fix :

 "Fatal error: Call to undefiled method pocketmine\inventory\CraftingManager::matchBrewingRecipe() in phar::///root/PocketMine-MP.phar/src/pocketmine/tile/BrewingStand.php on line 181 " 

Fix please.. :(

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Thanks alot!
So i don't have to do that.
Potions will work after food fix i think

**Comment by BlackShadow1** [comment]
It's a pleasure. You can test it? I think it works and open new bug..

**Comment by thebigsmileXD** [comment]
I will in 5 Minutes. Just arrived at home

**Comment by BlackShadow1** [comment]
Oh, ok. I think there are some bugs in the Brewing Stand, and i will to fix all of them XD

**Comment by thebigsmileXD** [comment]
They are placeable and destroyable in creative, in Survival the breaking takes atleast 2 times and doesn't drop anything. First time you place you see the inventory correctly, after rejoin its green. Old brewing stands dont need to be removed anymore, the latest fix atleast fixed the crashes. And can you remove the getSide(down) is transparent check on place please? Just saw that they also can float in singleplayer

**Comment by BlackShadow1** [comment]
Much tanks. I try to do all. In survival before the update the breaking takes 10 times, i don't know why 2 times now..

**Comment by thebigsmileXD** [comment]
because some errors were fixed, like the Tile wasn't even created.

**Comment by BlackShadow1** [comment]
Ah, yes.

**Comment by BlackShadow1** [comment]
Brewing Stand drop aren't bugged, they drop correctly if destroyed with a wood pickaxe, tested.

**Comment by thebigsmileXD** [comment]
Hmm, i still have to break them 10 times or so with pickaxe

**Comment by BlackShadow1** [comment]
I don't understand why D:

**Comment by thebigsmileXD** [comment]
Me neither.. The code seems correct

**Comment by BlackShadow1** [comment]
Yes, it's this the problem! The code is correct and the bug is very misterious..

**Comment by thebigsmileXD** [comment]
Maybe because of the creepy hitbox?

**Comment by BlackShadow1** [comment]
I don't know.. Try you to fix it.

**Comment by thebigsmileXD** [comment]
Oh god, no idea.

**Pull request merged**
