### PR TITLE
Fixed weird display stile on Ban

### PR DESCRIPTION
**Pull request by robske110**
I have tested this, it does work!
### The command
ban Test3 Test
### Was resulting into
[13:01:12] [INFO]: Test3[/92.72.232.130:19132] logged out due to Kicked by admin. Reason: Banned by admin. Reason: Test
### Client was displaying:
Kicked by admin. Reason: Banned by admin. Reason: Test
### Now changed to:
Kicked by admin. Reason: Test
## You cannot change the "kicked by admin" part as it is defined by the kick command!

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
The text is wrong

**Comment by robske110** [comment]
Wich "Text" is wrong?

**Comment by matcracker** [comment]
You write $player->kick("$reason") but it writes $reason and not the content of $reason.

**Comment by robske110** [comment]
I have tested it and it DOES work!

**Comment by matcracker** [comment]
If you don't put any reason works but if you put a reason it writes "Banned by admin. Reason: $reason".
You should write $player->kick($reason);

**Comment by robske110** [comment]
But why is it working then?
Look at the screenshot...

**Comment by robske110** [comment]
Oops accedently closed it...

**Comment by robske110** [comment]
What is up with this request now
Again
IT DOES WORK

**Comment by thebigsmileXD** [comment]
It works because its php. $'s in strings are combined. But thats wether a lack of knowledge or a code style error.

**Comment by matcracker** [comment]
This I would to say!

If you replace ("$reason") with ($reason) we probably merge it :)
Il 15/dic/2015 19:16, "Dan" <notifications@github.com> ha scritto:

**Comment by robske110** [comment]
Ok, sorry guys I am very new to php and this is one of my first PRs in php... i will remove the "" ;)

**Comment by thebigsmileXD** [comment]
When you don't know php you are wrong here.
We won't merge this request. Its invalid

**Comment by robske110** [comment]
That's rude! I didn't say I do not know it! I said i am new to it... And this pull request may be irrelevant but not invaild! It does work and i did a little mistake, wich didn't even affect the result!

**Comment by keithkfng** [comment]
Seriously, it is relevant and it is valid, he just messed it up a bit...

**Comment by thebigsmileXD** [comment]
Its not rude. If you don't understand PHP, go away, learn PHP and don't make invalid requests.
When you understand how to code than you can come back.
@keithkfng I don't like this person to do any more invalid pull requests.

**Comment by thebigsmileXD** [comment]
Seems like you don't understand. You just lost my support on this repo and the IC-Team.
Goodbye.

**Comment by robske110** [comment]
I did one little mistake and you want to ban me? That mistake didn't even mess up anything it did work. And I fixed it now... And maybe you learn programming by DOING... Ok, if you don't want me I will go away :(

**Comment by keithkfng** [comment]
@thebigsmileXD LOL really? I didn't know that

**Comment by keithkfng** [comment]
Let me just lock this to avoid more arguments.

**Comment by matcracker** [comment]
Are serious? -.-  Do you leave the team because one guy create a pull request and he doesn't know PHP?
He changes only an if selection and he wrong for " ", so keep calm and return back :+1:

**Pull request closed without merging**
