### PR TITLE
Updated all recipes & Sorted

### PR DESCRIPTION
**Pull request by kiyoshi-kurosaki**
So i updated all recipes, added new recipes & sorted out from Shapeless over Shaped to BigShaped.

### CODE REVIEW

**Comment by robske110** [comment]
Building failed...

**Comment by kiyoshi-kurosaki** [comment]
Yes i know...i hope the problem is not comming from me...?

**Comment by robske110** [comment]
That commit broke it https://github.com/ImagicalCorp/ImagicalMine/commit/263ea8563f5f99d42fb8e0a6c466d9cd12bcdbe8

**Comment by robske110** [comment]
Wait for @ChalkPE to fix it then merge the fixes to your branch and then hopefully this or will be merged

**Comment by kiyoshi-kurosaki** [comment]
Yeah i can wait for it :D but you can confirm it if merged thanks :D 

Regards

**Comment by BlackShadow1** [comment]
RedstoneOre.PHP need public function construct, that's the error, i think.

**Comment by kiyoshi-kurosaki** [comment]
I hope that will fix it @robske110 @ChalkPE 

-> https://github.com/ImagicalCorp/ImagicalMine/pull/659

**Comment by robske110** [comment]
Merge #659 in this PR-Branch!

**Comment by PocketKiller** [comment]
Hmm...

**Comment by Anonymous4Life123** [comment]
taha.... wow u are so busy with school -_-

**Comment by Anonymous4Life123** [comment]
anyway when i install ImagicalMine on linux with the wget it only gives me a .zip of imagical. how do i run it with the .zip...

**Comment by omgA4L** [comment]
btw it was on linux and i did all steps correctly.

**Comment by kiyoshi-kurosaki** [comment]
@BlackShadow1 
@PocketKiller 
Now it can be merged :D

**Pull request merged**
