### PR TITLE
Redstone related item crafting

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Cool!

**Comment by BlackShadow1** [comment]
Now, the player can crash the server with the redstone item, very cool xD

**Comment by thebigsmileXD** [comment]
What?

**Comment by thebigsmileXD** [comment]
redstone is really stable and doesn't cause crashes anymore

**Comment by BlackShadow1** [comment]
Oh, well. Is your food branch finished?

**Comment by thebigsmileXD** [comment]
no

**Comment by BlackShadow1** [comment]
Ok, I'm waiting you finish it for make the potion functionally.

**Comment by NycuRO** [comment]
Please fix the Brewing Stand. It's buggy . I created potion and not give in inventory.

**Comment by NycuRO** [comment]
And fix crafting table . It's not craftable all. e.g. : Diamond block not exist in crafting recipe for add 9 diamonds.

**Comment by BlackShadow1** [comment]
Ok, how many crafting recipe aren't in the code?

**Comment by thebigsmileXD** [comment]
Almost every

**Comment by MCPEPIG** [comment]
Ingots can't be crafted into Blocks and Blocks can't be drafted into ingots. Problem with the registerIngots function

**Comment by keithkfng** [comment]
Report bugs on the issue tracker please.

**Pull request merged**
