### PR TITLE
Improve IronTrapdoor

### PR DESCRIPTION
**Pull request by matcracker**
Title say all :+1:

### CODE REVIEW

**Comment by keithkfng** [comment]
Sometimes I wonder why you left the team LOL

**Comment by MCPEPIG** [comment]
Have you tested? :3

**Comment by matcracker** [comment]
@keithkfng because I've got some problems and I didn't want to give inactivity. If you reinvite me I  would be honored :)

**Comment by matcracker** [comment]
Oh yes, I test it before commit this pull request :+1:

**Comment by keithkfng** [comment]
It would be an honour to invite you back...

**Comment by matcracker** [comment]
Thanks a lot!

**Pull request merged**
