### PR TITLE
Update Player.php

### PR DESCRIPTION
**Pull request by Godsoft029**

### CODE REVIEW

**Comment by Driesboy** [comment]
work

**Comment by robske110** [comment]
Still crashes

**Comment by rj0495** [comment]
This provides a solution for getting the skin length. Maybe worth putting in a local copy to check actual length. But it shouldn't really be merged.

**Comment by Godsoft029** [comment]
Yep thats only to get the actual format. Probably I will remove it or I will change it that it only shows in debug mode

**Comment by rj0495** [comment]
If you can set to DEBUG only I will merge.

**Comment by Godsoft029** [comment]
I think thats it

**Comment by Driesboy** [comment]
no crash on spawn now 
we have now a crash after 20 sec

**Comment by Godsoft029** [comment]
Where do you get the phar?

**Comment by Driesboy** [comment]
from your fork

**Comment by Godsoft029** [comment]
How to zip to phar?

**Comment by Driesboy** [comment]
src in pocketmine and devtools make phar

**Comment by Godsoft029** [comment]
Thank you

**Comment by thebigsmileXD** [comment]
You don't. We set up jenkins, there are always the latest builds. See in the repo, the link is right on top

**Comment by Driesboy** [comment]
but @Godsoft029 version not

**Pull request closed without merging**
