### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TylerAndrew**
Lol i believe this was a accident

### CODE REVIEW

**Comment by keithkfng** [comment]
WTF?! You will not change the README. Only I am allowed to change the README thank you very much. That was not an error.

**Comment by ZombiePower** [comment]
woops..... should have told me -.-

**Comment by keithkfng** [comment]
Soz LOL

**Comment by TylerAndrew** [comment]
Nice community we got here... Btw I tested the 19133 and the thing didn't. Even come up so I tested 19132 and it doesn't work if you don't like that I tried to help then don't comment insulting things especially when it was a accident .... Some rude ass people I swear....

**Pull request merged**
