### PR TITLE
Fixed some problem  with trapdoor

### PR DESCRIPTION
**Pull request by matcracker**
- Fixed RakLib error
- Re-added sound when the trapdoor is opening (no Redstone)
- Fix some space in fuction "onRedstoneUpdate"

### CODE REVIEW

**Comment by aodzip** [comment]
Have you test this?

**Comment by matcracker** [comment]
Yes, I test it without plugins :+1:

**Comment by thebigsmileXD** [comment]
Finally someone found a fix.

**Comment by aodzip** [comment]
still have bug ... in some cases

**Comment by matcracker** [comment]
Yes, it's not complety fixed, I wrote in the comment: if the trapdoor is placed in the top it creates a small mistake but if placed in the bottom of the block it works good

**Comment by thebigsmileXD** [comment]
Whats wrong with the top block half? What error do you get?

**Comment by matcracker** [comment]
Any error, but if you place on the top when it's opened doesn't go in the bottom but go left or right depending on face of block.

**Comment by aodzip** [comment]
It can use the same way I fix the lever :
1.Test every meta and write it down on a paper
2.change the code.

LOL

**Comment by matcracker** [comment]
Yes, I'm writing all the combinations of 2345 xD

**Comment by aodzip** [comment]
meta may up to 15(in lever case)

**Comment by matcracker** [comment]
Sorry if I ask here but where I can find an updated list of a current bugs (one issue is not updated)? I want to help you to try fix and implementing some things :D

**Comment by aodzip** [comment]
Issue Tracker

If you want help , please remember until you understand how redstone work in this repo . Don't change any code about Redstone

**Comment by thebigsmileXD** [comment]
The "current list of bugs for ImagicalMine" you mean?
What isn't updated?

**Comment by matcracker** [comment]
Don't worry, I was in this team but I left for some problems but now I'm again active.

**Comment by matcracker** [comment]
The pressure plates for example, I try the last build and works for me :)

**Comment by thebigsmileXD** [comment]
They finally work again. Yay

**Comment by matcracker** [comment]
:)

**Pull request merged**
