### PR TITLE
Update SimpleCommandMap.php

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
How have you found this? Anyways, i'll merge, thats a critical fix

**Comment by BlackShadow1** [comment]
There is a branch, Weather-matcracker, why "thats a critical fix"?

**Comment by matcracker** [comment]
Yes, but I'm currently work, I know this.

**Comment by thebigsmileXD** [comment]
Because the reload command or the weather command could have caused crashes

**Comment by matcracker** [comment]
Yes, but this branch isn't compiled o.O

**Comment by BlackShadow1** [comment]
I think no, i had try to do WeatherCommand much time ago, in my format didn't crash.

**Comment by thebigsmileXD** [comment]
But! Just tested.. /reload -> works
/weather -> unknown command
Shouldn't it say "class not found"? because theres no weather command class, but the command is registered

**Comment by matcracker** [comment]
Yes but don't test this branch! I know that doesn't work

**Comment by thebigsmileXD** [comment]
I am in the master branch.

**Comment by BlackShadow1** [comment]
Lol. @matcracker do you need a help with this branch?

**Comment by matcracker** [comment]
At the moment no, it's christmas and I'm not working but tonight I
continue.

**Comment by BlackShadow1** [comment]
Ok.

**Comment by thebigsmileXD** [comment]
Merry christmas :gift:

**Comment by matcracker** [comment]
Thanks likewise :gift: :D

**Pull request merged**
