### PR TITLE
Revert "Fixes SnowLayer bug"

### PR DESCRIPTION
**Pull request by rj0495**
Reverts ImagicalCorp/ImagicalMine#248 Forgot a crucial part of the code

### CODE REVIEW

**Comment by aodzip** [comment]
What happened?

**Comment by rj0495** [comment]
I forgot that I overrided the default so you cannot place a single snow
layer.

**Comment by aodzip** [comment]
Oh , You change the setBlock

**Comment by thebigsmileXD** [comment]
Also, i just realized: this would be wrong.
Snow layers have a different height then snow block

**Comment by rj0495** [comment]
Yeah, I forgot and committed this. I am gonna rewrite today

**Pull request merged**
