### PR TITLE
Support for ExpCommand

### PR DESCRIPTION
**Pull request by BlackShadow1**

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Thanks, already forgot about it.

**Comment by BlackShadow1** [comment]
It's a pleasure, of course, but there is a crash with the command, when you use /xp 101(or higer) <player> the server crash in a bit of line, setExp is the bug..I'm posting this on the issue tracker.

**Comment by thebigsmileXD** [comment]
Thanks :+1:

**Comment by BlackShadow1** [comment]
;)

**Pull request merged**
