### PR TITLE
Create SlimeBlock.php

### PR DESCRIPTION
**Pull request by PocketServers**
Slimeblock for upadte 0.14.0

### CODE REVIEW

**Comment by aodzip** [comment]
Not  a good code
seems a copy of clay

**Comment by matcracker** [comment]
Please, if continue ban from the repository D:
How long the SlimeBlock have the name Clay Block? Hahaha

**Comment by keithkfng** [comment]
This guy is copying code like crazy. He even submitted a fix from IM to PM but didn't mention us - and it started all this commotion...

**Comment by thebigsmileXD** [comment]
And it was the old, not so good code.

**Comment by PocketServers** [comment]
code erro sorry i fix the clay part

**Comment by PocketServers** [comment]
<?php
/*
 *
 *  _                       _           _ __  __ _             
 * (_)                     (_)         | |  \/  (_)            
 *  _ _ __ ___   __ _  __ _ _  ___ __ _| | \  / |_ _ __   ___  
 * | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ 
 * | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/ 
 * |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___| 
 *                     __/ |                                   
 *                    |___/                                                                     
 * 
 * This program is a third party build by ImagicalMine.
 * 
 * PocketMine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author ImagicalMine Team
 * @link http://forums.imagicalcorp.ml/
 * 
 *
*/
namespace pocketmine\block;
use pocketmine\item\Item;
use pocketmine\item\Tool;
class SlimeBlock extends Solid{
	protected $id = self::SLIME_BLOCK;
	public function __construct(){
	}
	public function getHardness(){
		return 0.6;
	}
	public function getToolType(){
		return Tool::TYPE_SHOVEL;
	}
	public function getName(){
		return "Clay Block";
	}
	public function getDrops(Item $item){
		return [
			[Item::CLAY, 0, 4],
		];
	}
}

**Comment by PocketServers** [comment]
<?php
/*
 *
 *  _                       _           _ __  __ _             
 * (_)                     (_)         | |  \/  (_)            
 *  _ _ __ ___   __ _  __ _ _  ___ __ _| | \  / |_ _ __   ___  
 * | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ 
 * | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/ 
 * |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___| 
 *                     __/ |                                   
 *                    |___/                                                                     
 * 
 * This program is a third party build by ImagicalMine.
 * 
 * PocketMine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author ImagicalMine Team
 * @link http://forums.imagicalcorp.ml/
 * 
 *
*/
namespace pocketmine\block;
use pocketmine\item\Item;
use pocketmine\item\Tool;
class SlimeBlock extends Solid{
	protected $id = self::SLIME_BLOCK;
	public function __construct(){
	}
	public function getHardness(){
		return 0.6;
	}
	public function getToolType(){
		return Tool::TYPE_SHOVEL;
	}
	public function getName(){
		return "Clay Block";
	
		];
	}
}

**Comment by DRedDogPE** [comment]
No, you didnt fix the Clay part because it still says clay block

**Comment by PocketServers** [comment]
<?php
/*
 *
 *  _                       _           _ __  __ _             
 * (_)                     (_)         | |  \/  (_)            
 *  _ _ __ ___   __ _  __ _ _  ___ __ _| | \  / |_ _ __   ___  
 * | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ 
 * | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/ 
 * |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___| 
 *                     __/ |                                   
 *                    |___/                                                                     
 * 
 * This program is a third party build by ImagicalMine.
 * 
 * PocketMine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author ImagicalMine Team
 * @link http://forums.imagicalcorp.ml/
 * 
 *
*/
namespace pocketmine\block;
use pocketmine\item\Item;
use pocketmine\item\Tool;
class SlimeBlock extends Solid{
    protected $id = self::SLIME_BLOCK;
    public function __construct(){
    }
    public function getHardness(){
        return 0.6;
    }
    public function getToolType(){
        return Tool::TYPE_SHOVEL;
    }
    public function getName(){
        return "Slime Block";

        ];
    }
}

**Comment by PocketServers** [comment]
now should work

**Comment by DRedDogPE** [comment]
Slimeblock isn't even in the game yet

**Pull request closed without merging**
