### PR TITLE
redstone its stabel

### PR DESCRIPTION
**Pull request by lolcraftboy14**
Its very stabel dan you tink

### CODE REVIEW

**Comment by aodzip** [comment]
What the hell is this？

**Comment by aodzip** [comment]
I Will Close This

**Comment by thebigsmileXD** [comment]
Right

**Comment by PocketKiller** [comment]
he's trying to merge Tests with Master. then, why not commit it?

**Comment by PocketKiller** [comment]
Tests branch not updated yet

**Comment by keithkfng** [comment]
How the heck did he submit a pull request for the branch?

**Comment by thebigsmileXD** [comment]
Still, INVALID

**Pull request closed without merging**
