### PR TITLE
Fixed the SnowLayer Bug

### PR DESCRIPTION
**Pull request by rj0495**
I actually fixed it this time.

### CODE REVIEW

**Comment by aodzip** [comment]
Have you test it?

**Comment by rj0495** [comment]
I am right now. Please allow me a few mins

**Comment by thebigsmileXD** [comment]
Same thing as i said in the last commit. SnowBlock will be a temporary fix. the height is different (or bounding box)

**Comment by aodzip** [comment]
yes , i just merge and test 
the top layer snow still buggy

**Comment by thebigsmileXD** [comment]
I know why now.. Oh, damn fail..

**Comment by rj0495** [comment]
Right, I'm testing right now

**Pull request merged**
