### PR TITLE
Added ClearSky changes

### PR DESCRIPTION
**Pull request by keithkfng**
NOTE: Sorry - no commit history :( There were conflicts with the shell
Okay, a lot of changes were reverted, but we can fix them later...
@aodzip what do you think?

### CODE REVIEW

**Comment by keithkfng** [comment]
OMG it doesn't lag at all! Brilliant!

**Comment by dterweij** [comment]
Nice. Then i just wait till all is backported in before I test :)

**Comment by ZombiePower** [comment]
ASCII cant cause lag -_-

**Comment by keithkfng** [comment]
@ZombiePower yes it does - it takes time to print each line, remember?

**Comment by keithkfng** [comment]
http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine-NoLag/

**Comment by aodzip** [comment]
There is too many conflicts between ClearSky and ImagicalMine
Copy the whole Project is better than try to merge them together . That's the truth ..

**Comment by keithkfng** [comment]
I'll merge this and see how you go. Yes, you are correct indeed, they are both for separate purposes.

**Comment by thebigsmileXD** [comment]
It does. Loading the files takes 0.00002 seconds more. Remember gow many files are there ;)

**Comment by thebigsmileXD** [comment]
@keithkfng Please do what aodzip said.. Delete everything except the readme and so on and copy the WHOLE PROJECT. Already found messed up things (furnace, orbs, drops)

**Comment by keithkfng** [comment]
I won't delete everything - but I will make a new branch and make it the main branch, is that okay?

**Comment by thebigsmileXD** [comment]
I don't think that will actually makes sence.. its the same like copying

**Comment by keithkfng** [comment]
?

**Comment by thebigsmileXD** [comment]
nevermind. Nicely messed up :+1:

**Pull request merged**
