### PR TITLE
Changes to PlayerListPacket

### PR DESCRIPTION
**Pull request by jojoe77777**
Supports Slapper now. (Hopefully (My iPad isn't working so I can't test))

### CODE REVIEW

**Comment by ZombiePower** [comment]
:+1:

**Comment by thebigsmileXD** [comment]
So you removed PlayerListPacket. How to see the online players now?

**Comment by ZombiePower** [comment]
btw my :+1: was just because Jojoe77777 made a commit. I didnt read a single bit of it xD

**Comment by keithkfng** [comment]
Added it back I think ✌🏻️

**Comment by ZombiePower** [comment]
@jojoe77777 any ways, you can update it for ImagicalMine and upload it on the forums?

**Comment by keithkfng** [comment]
I don't think it'll be any better if we change the actual software code. Maybe as @ZombiePower said edit the plugin... But it isn't the plugin's fault, is it?

**Comment by ZombiePower** [comment]
@keithkfng no

**Comment by keithkfng** [comment]
Exactly... So how can he edit the plugin when it's not the plugin's fault? Something to do with ImagicalMine then.

**Comment by ZombiePower** [comment]
well... there can be ways

**Comment by jojoe77777** [comment]
> thebigsmileXD commented 25 minutes ago
> So you removed PlayerListPacket. How to see the online players now?

I only removed PlayerListEntry. But I forgot to do some other things...

**Pull request merged**
