### PR TITLE
Fix for #383

### PR DESCRIPTION
**Pull request by BlackShadow1**
Can anyone test if it work to all? I think there is a bug, Before i test it and the night time is 13000 and now 20000 in a different high level, new bug incoming?

### CODE REVIEW

**Comment by matcracker** [comment]
This can resolve for the moment but it doesn't correct

**Comment by BlackShadow1** [comment]
@matcracker why?

**Comment by matcracker** [comment]
Because in MC:PC the ticks are correct as Pocketmine 0-24000. Or it's a MC:PE bug or I don't know...

**Comment by BlackShadow1** [comment]
Oh... I don't know..

**Comment by ZombiePower** [comment]
wrong times xD

**Pull request closed without merging**
