### PR TITLE
Why 2 $this->hasCompoundTag @ZombiePower??

### LINKED ISSUE #460: New crafting bug? old one seems to be fixed
The bug that would remove items from your inventory when crafting was fixed..but now..somewhere above dev #224 there is a bug stopping all crafting. You craft the item and it stays for a sec until you try to place it or use it. I tried this with no people on the server as well to make sure it wasn't lag and there seems to be no trick or anything to get crafting to work.

### PR DESCRIPTION
**Pull request by BlackShadow1**
Fix #460

### CODE REVIEW

**Comment by PocketKiller** [comment]
are you trying to fix the crafting bug? i already tried that, not working.

**Comment by BlackShadow1** [comment]
try this ;)

**Comment by matcracker** [comment]
But is correct this..

**Comment by BlackShadow1** [comment]
Well. Close #460

**Comment by PocketKiller** [comment]
why? it's not working.

**Comment by BlackShadow1** [comment]
This work. After the commit of @ZombiePower all crafting working, now working with this, i had test this just now. Are you tested this? Test it. Just copy and paste the function, delete the function in src/pocketmine/item/Item.php and paste. Try. It work.

**Comment by PocketKiller** [comment]
@BlackShadow1 you might just have thinked it worked like i did, craft a block and try to place it.

**Comment by BlackShadow1** [comment]
yes.. sorry @PocketKiller

**Comment by ZombiePower** [comment]
I don't know tf that makes sense...

**Pull request merged**
