### PR TITLE
Linux installation

### PR DESCRIPTION
**Pull request by omgA4L**
when i install imagical mine on ubuntu linux it only gives me the .zip. how am i suppose to make the server work with that one .zip?

### CODE REVIEW

**Comment by omgA4L** [comment]
ugh im new to github so idk where all those stuff from keith came in from.

**Comment by PocketKiller** [comment]
don't be dump. (wrong place, this should not be a pull request)

**Comment by omgA4L** [comment]
taha go on kik to help pls.

**Comment by PocketKiller** [comment]
Who are you? and stop going off-topic.

**Comment by omgA4L** [comment]
lmao im Anonymous4Life :p help me with this problem on kik cuz github is confusing to work with

**Pull request closed without merging**
