### PR TITLE
Food merge

### PR DESCRIPTION
**Pull request by thebigsmileXD**
Maybe GitHub still likes me after i raged?

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
After hours of trouble with GitHub..
Who wants this to be merged?

**Comment by thebigsmileXD** [comment]
@NycuRO It had many conflicts because the branch wasn't up to date

**Comment by keithkfng** [comment]
VICTORY! XD

**Comment by thebigsmileXD** [comment]
@keithkfng Victory over GitHub

**Comment by thebigsmileXD** [comment]
Haven't tested yet.. I'll test first

**Comment by matcracker** [comment]
Merge merge merge! xD

**Comment by BlackShadow1** [comment]
@thebigsmileXD you're the best :P

**Comment by MCPEPIG** [comment]
Magma Cream isnt food but was added in this PR, let's eat Magma Cream!

**Comment by matcracker** [comment]
Yeah! xD

**Comment by thebigsmileXD** [comment]
@matcracker Nope
@MCPEPIG -.- MagmaCream ! instanceof Food

Also, we can't merge this yet. It contains bugs.. creepy bugs.

**Comment by thebigsmileXD** [comment]
Also i think after updating some files got corrupted..

**Comment by keithkfng** [comment]
Can we actually merge this?

**Comment by thebigsmileXD** [comment]
No.. As i said, there are plenty of bugs.

**Comment by keithkfng** [comment]
-_-

**Pull request merged**
