### PR TITLE
Fixed stair problem

### PR DESCRIPTION
**Pull request by MCPEPIG**

### CODE REVIEW

**Comment by keithkfng** [comment]
LOL why don't you just commit to the master branch...

**Comment by MCPEPIG** [comment]
I left the team.

**Comment by MCPEPIG** [comment]
Wait nvm ._.

**Comment by keithkfng** [comment]
Still shows you're a team member LOL

**Comment by MCPEPIG** [comment]
I think I left successfully this time, or at least it said I left unlike last time.

**Comment by robske110** [comment]
?

**Comment by MCPEPIG** [comment]
@robske110 Can you even read?...

**Pull request merged**
