### PR TITLE
Update PlayerExperienceChangeEvent.php

### PR DESCRIPTION
**Pull request by Naniiii**
It is action, not *auction*.

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Auction would've been funny. Because its like auctioning xp to the player. Thanks for the fix, i'll check in genisys

**Comment by Naniiii** [comment]
It is incorrect in genisys as well.

**Comment by thebigsmileXD** [comment]
@PeratX

**Comment by PeratX** [comment]
@thebigsmileXD He is right. It is my type error...

**Comment by thebigsmileXD** [comment]
@PeratX that can happen

**Comment by PeratX** [comment]
I have fixed it :)

**Pull request merged**
