### PR TITLE
0.13.1 updates/support

### PR DESCRIPTION
**Pull request by keithkfng**
I only updated the version in the PocketMine source file. Team members - do more edits by pushing to the 0.13.1-update branch.

### CODE REVIEW

**Comment by SavionLegendZzz** [comment]
wait so mcpe 0.13.1 is out or our we preparing?

**Comment by keithkfng** [comment]
@TexusDark how? Changes the versioning only.

**Comment by keithkfng** [comment]
@SavionLegendZzz preparing. Expect it to be out in a couple of days.

**Comment by keithkfng** [comment]
Someone said something about skins not working again when updating. I'll test it.

**Comment by Driesboy** [comment]
skin corrupt

**Comment by adamascj2** [comment]
client crashing after 1 min

**Comment by TexusDark** [comment]
@keithkfng I don't know but I have update my PocketMine version :)

**Comment by dterweij** [comment]
Skin error on Windows 10 Beta Minecraft. Used the temp-skinfix release to play from windows 10 Beta Minecraft.

**Comment by Godsoft029** [comment]
use the master branch

**Comment by thebigsmileXD** [comment]
I am only having this issue when i use the pc skin models with overlays etc.
The skin model where the left/right arms can be different.
Mcpe and mc10 don't support this.

**Pull request merged**
