### PR TITLE
smelting exp

### PR DESCRIPTION
**Pull request by wrewolf**
Implement items getSmeltingExp()

### CODE REVIEW

**Comment by BlackShadow1** [comment]
Glass.php has two }

**Comment by wrewolf** [comment]
@BlackShadow1 fixed, question in ItemBlock.php

**Comment by wrewolf** [comment]
Tested, some ore not crash server. Complex test in progres.

**Comment by BlackShadow1** [comment]
@wrewokf NetherQuartz.php has two } too xD

**Comment by matcracker** [comment]
:+1: Nice work!

**Comment by thebigsmileXD** [comment]
Doesn't match ClearSky anymore, sorry. Too many conflicts to merge our latest fixes :)

**Comment by thebigsmileXD** [comment]
But good job anyways

**Comment by keithkfng** [comment]
Anyone an experienced Java programmer here?

**Comment by thebigsmileXD** [comment]
Over here. Made forge mods and bukkit plugins once.

**Comment by keithkfng** [comment]
What about a proxy? Too challenging for you I guess.

**Comment by thebigsmileXD** [comment]
Challenging: yes. Too ch.. No. But i do not support that shit language Java anymore. There are proxy softwares.. Oh wait, (warning sarcasm) they dont work 😳 ooh what should we dooo?

**Comment by wrewolf** [comment]
What kind of conflict?
If the method of issuing the experience has not changed, you can copy and paste perensti it to you and close the query.
Or I will correct, but I have to understand that to be corrected.

**Comment by thebigsmileXD** [comment]
Do you know that getSmeltingExperience only works on items? ;)

**Comment by BlackShadow1** [comment]
Lol!

**Comment by thebigsmileXD** [comment]
> Do not ask me on ANYTHING related to this. I don't give any warranty to this code.

**Pull request merged**
