### PR TITLE
Update Item.php

### PR DESCRIPTION
**Pull request by PocketServers**
New update for the item list fixed item listing and fixed rail item bugs.

### CODE REVIEW

**Comment by FienixEC** [comment]
Whats the latest .phar? Could i get a link? Thanks.

**Comment by MCPEPIG** [comment]
This commit has errors.

**Comment by PocketKiller** [comment]
@MCPEPIG Maybe not, Travis has some errors with itself.

**Comment by keithkfng** [comment]
Checkout Jenkins. It might have a different output.
EDIT - i haven't made it compile PR'S LOL

**Pull request closed without merging**
