### PR TITLE
SomeRedstoneThings

### PR DESCRIPTION
**Pull request by aodzip**
Working in progress

### CODE REVIEW

**Comment by aodzip** [comment]
This branch has conflicts 
I will create comment only when I test it is really work.

**Comment by thebigsmileXD** [comment]
.. Wow.. I hate it if there are 2 people working on the same thing \*rofl\*
That this happens i such a big project is the most hilarious thing xD
I worked on Redstone the last hours, as you may see.
I like the interface Redstone.. But i think i already got redstone wire and torches working. Remember: every block except for transparent blocks and liquids can be powered.

**Comment by aodzip** [comment]
So . you suggest me update the latest code and make pr?
I really suggest use the interface Redstone and change the orginial Redstone.php -> RedstoneBlock.php
I make the Redstone Lamp work as well . but i will update my code first .
close this pr as u like

**Comment by thebigsmileXD** [comment]
Well, its not bad, but has some problems.
Lets say.. I work on the power inputs like pressure plates, buttons etc and you on the wire? Or should i do the wires?

**Comment by aodzip** [comment]
That easy , just check if  $down instanceof Redstone and use setPower in my code .
interface Redstone will make things goes easy

**Comment by thebigsmileXD** [comment]
But:
Setpower is implemented incorrectly in my oppinion..
And.. Well, idk, but redstone updates every 10 ticks or so? We'll have to add that then

**Comment by aodzip** [comment]
setPower is just a temporary solution

i think update the power in onUpdate is okay .
but i haven't test if it will cause lag.

I sould update my fork. 


PS
I use dictionary to talk with you lol.

**Comment by thebigsmileXD** [comment]
Also: you can place redstone below and on top of Redstone blocks, it will be powered :P thats why i test for all sides.
I'll create the DaylightSensor and pressureplates then, okay? And i'll try to fix Buttons. We need something that says its a power source i think, just dor the API.
And i might work on the ticking stuff too.. But i don't want to xD

**Comment by aodzip** [comment]
Implements Redstone,PowerSource ?
In my code i just set $this->power directly to show it is a powersource.

okay direct set is not a good way , we can't judge in code if it is a powersource

**Comment by aodzip** [comment]
okay i will refork and pull request the "interface Redstone" first .

it will be more convenience if I am a team member.

pr is okay too.

**Comment by aodzip** [comment]
GMT+8 here
it is 1:16 am 
I go to sleep.
tomorrow i will do the RedstoneWire.
PS: don't laugh at my stupid code i am just a noob

**Comment by aodzip** [comment]
I finish this part in latest code . close

**Comment by thebigsmileXD** [comment]
I don't laugh at you. My code wasn't better. i got an getPower loop .-.

**Comment by aodzip** [comment]
I make a Work-Well Redstone Wire . Try the latest code~

**Comment by aodzip** [comment]
It is your time to get buttons works!

**Comment by thebigsmileXD** [comment]
I'll work on buttons :P and levers now place correctly! :smile:
Uhm, when will we add the redstone tick?

**Comment by aodzip** [comment]
I have no idea 
I think we can get all the Redstone item work correct .
Then add tick in.

PS: should we add a "redstone=on" in server. properties?
If somebody don't want redstone lag his server he can turn off this

**Comment by thebigsmileXD** [comment]
Yup

**Comment by keithkfng** [comment]
Off-topic: make same for hunger - hunger=off?

**Comment by aodzip** [comment]
hahahah , maybe there is really someone need this

**Comment by keithkfng** [comment]
Yup - I've got people saying "I DONT WANT HUNGER" LOL

**Comment by thebigsmileXD** [comment]
Hunger? They don't want it? They should eat a snickers

**Comment by aodzip** [comment]
@thebigsmileXD 
We must use Redstone tick
or the server wil crash when the redstonewire connect too many
and the direct call to fetchPower will cause lag

**Comment by thebigsmileXD** [comment]
Yea. Happend to me also.. the wire updates instantly, right?

**Comment by aodzip** [comment]
yes
and if there is too many wire
onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->onUpdate->setPower->setBlock->

**Comment by thebigsmileXD** [comment]
AAAnd on every update it will call an update on all wires around.
so 2 wires already cause a crash..

**Comment by aodzip** [comment]
yes , set a death loop

**Comment by aodzip** [comment]
put redstone in a line will just cause Load =100% for a second
put redstone in a circle will cause a crash

**Comment by thebigsmileXD** [comment]
lol

**Comment by thebigsmileXD** [comment]
Lol? I haven't merged the master branch.. i just updated the flower pot and skull! GitHub bug?

**Comment by aodzip** [comment]
If this make things crazy , revert them

**Comment by MrDoni98** [comment]
https://github.com/PocketMinePlusPlus/PocketMinePlusPlus 
They fixed the door. please try too.

**Comment by aodzip** [comment]
Copy Code From everywhere

**Comment by thebigsmileXD** [comment]
@aodzip No idea where it came from..

**Comment by aodzip** [comment]
When you update your fork this commit will create in your fork.
When you merge it this will take to main repo.

**Comment by thebigsmileXD** [comment]
I never work on forks, thats why i wonder

**Comment by aodzip** [comment]
don't care this , the code didn't mess up.

How do you add a Redstone tick?
I have no idea.

**Comment by thebigsmileXD** [comment]
Me neither. I'll try, maybe a timer calling all redstone blocks to update or a new blockupdateevent called redstoneupdateevent, then updating the blocks (re-placing them) onRun($currentTick) should work..

**Comment by thebigsmileXD** [comment]
..Just tested Redstone..
I am proud of you and your work!
I can even place a circle of redstone, it will work!
Todo/in progress/bugs:
RedstoneLamps drop on non solid blocks, i can't place redstone wire on top of upside-down-slabs or glowstone, levers and buttons still bug, can't place daylight sensor, tnt and doors/gates don't react on redstone

I'll check out the redstone lamp bug and buttons/levers now.
Oh, and sometimes, when a redstone wire goes up and you then power the lower part the power isn't updated for the up line, only for the y-level the first powered redstone is. But down works like a charm

**Comment by PocketKiller** [comment]
@aodzip :+1:

**Comment by keithkfng** [comment]
@aodzip OMG I am so stupid, why didn't I add you earlier? Sorry... LOL

**Comment by aodzip** [comment]
@keithkfmng earlier I am just a mini bug fixer😁

**Comment by aodzip** [comment]
I create
namespace Redstone RedstoneTools
A new function
isActivitedByRedstone()

I think if want button and lever work
I need a new interface 
RedstoneCharger

and some new functions

**Comment by thebigsmileXD** [comment]
Call it redstonesupplier or so.. charger is somehow.. hmm

**Comment by aodzip** [comment]
@thebigsmileXD
Go Buttons
We can open iron door soon!

**Comment by thebigsmileXD** [comment]
Buttons are lame.. Go pressureplates!

**Comment by aodzip** [comment]
@thebingsmileXD
How to use your setPower();?
if we can save power in a block data
we don't need calculate and scan all block every time
this will reduce lag!

**Comment by aodzip** [comment]
@thebigsmileXD 
judge a block is charged will be easy and fast if we can save power data in a block data

**Comment by thebigsmileXD** [comment]
I used setpower because levers and pressure plates can change their power state

**Pull request closed without merging**
