### PR TITLE
Fix for #402

### PR DESCRIPTION
**Pull request by BlackShadow1**
by @onebone in the pocketmine pull request. If he doesn't like, revert this.

### CODE REVIEW

**Comment by matcracker** [comment]
Fix the indetation

**Comment by BlackShadow1** [comment]
indetation??

**Comment by matcracker** [comment]
Indentation*

**Comment by BlackShadow1** [comment]
I don't understand ..

**Comment by thebigsmileXD** [comment]
Spacing

**Comment by BlackShadow1** [comment]
Ah, ok.

**Comment by BlackShadow1** [comment]
But where? lol

**Comment by BlackShadow1** [comment]
now working.

**Comment by BlackShadow1** [comment]
Ok, now working completely. Can anyone merge it?

**Pull request merged**
