### PR TITLE
player respawn fix

### PR DESCRIPTION
**Pull request by smyb**

### CODE REVIEW

**Comment by smyb** [comment]
players are respawning correctly (tested) . the cause of the bug was the health becames negative .

**Comment by smyb** [comment]
please make indent size 4

**Comment by matcracker** [comment]
Esatto, bastava quello!

**Comment by thebigsmileXD** [comment]
Could you please write english?

**Comment by matcracker** [comment]
Yes, sorry, I said that for fix the health could be this pull, but first I want to test better.

**Comment by thebigsmileXD** [comment]
Hasn't @MCPEPIG tried exactly the same?

**Comment by matcracker** [comment]
On which commit?

**Comment by smyb** [comment]
he didn't

**Comment by smyb** [comment]
@matcracker this fix the player respawn bug when the health becomes negative

**Pull request merged**
