### PR TITLE
Fix #223

### LINKED ISSUE #223: SMode: You can suffocate in redstone dust
If redstone dust didn't float this problem would be solved.
Also you can't break redstone dust.

### PR DESCRIPTION
**Pull request by aodzip**
That is it

### CODE REVIEW

**Comment by MCPEPIG** [comment]
:+1:

**Comment by MCPEPIG** [comment]
Have you tested it yet?

**Comment by thebigsmileXD** [comment]
Theres 1 mistake: you can still place redstone on redstone.
1st: redstone implements transparent.
2nd: you cant place redstone wire on leaves.
3rd: its flowable
;) maybe i'll do it tomorrow.

**Comment by aodzip** [comment]
OK I Make it

**Comment by MCPEPIG** [comment]
and where's implement Transparent?

**Comment by MCPEPIG** [comment]
and I don't think you can place redstone wires on anything Transparent, so just check if the block beneath is instanceof Transparent (Tell me if I'm wrong)

**Comment by aodzip** [comment]
If I add implement Transparent
will cause an error I can't solve it
So I add a public function isTransparent();

I think you are right! Just check instanceof Transparent

**Comment by aodzip** [comment]
Flowable is extend as Transparent
Check block\Flowable.php

**Comment by aodzip** [comment]
(PS:I am Chinese , poor English)

**Comment by MCPEPIG** [comment]
oops

**Comment by thebigsmileXD** [comment]
-.-" i already said so

**Comment by thebigsmileXD** [comment]
Thanks :)

**Pull request merged**
