### PR TITLE
Some Small Changes

### PR DESCRIPTION
**Pull request by zzm317**
Added Boat
Added Weather
Fixed Anvil
Added zhs.ini(中文简体)

### CODE REVIEW

**Comment by aodzip** [comment]
This Man Must Add into  our Team 
@keithkfng

**Comment by aodzip** [comment]
I have test this 
And Who care ASCII arts ? lol
Add ASCII Art Later

**Comment by matcracker** [comment]
Weather and boats is bugged...

**Comment by aodzip** [comment]
Better than none

**Comment by aodzip** [comment]
We can fix these later

**Comment by keithkfng** [comment]
Too rushed.... XD
Still good though. I'll test them today.

**Comment by aodzip** [comment]
At least I see rain ,
I can sit into the boat , drive it away
That is a great improve , isn't?

**Comment by matcracker** [comment]
Yes but keep calm @aodzip xD . I, but I think we, want to add things one by one because could be confused.

**Comment by matcracker** [comment]
Yes but when is day there always are the thuders :/

**Comment by aodzip** [comment]
just some if can fix it .

**Comment by Jelly9912** [comment]
Crafting is still so buggy

**Comment by matcracker** [comment]
No wait, I'm rewriting it.

**Comment by thebigsmileXD** [comment]
Boats.. So entities. I wait for lag and servers crashing

**Comment by PocketKiller** [comment]
@zzm317 haven't seen you awhile!

**Pull request merged**
